### PR TITLE
feat(zorp): add zorp container and configuration

### PR DESCRIPTION
**Pull request by blint**
- added key provisioning
- added reverse proxying for user-exposed services
- removed the explicit exposure of management ports
- edited application configs to update them for reverse proxying

### CODE REVIEW

**Comment by blint** [comment]
As ansible_user_data.yml is now removed, what would be the preferred way of passing configuration options to templating? I would like to rebase to the current 0.3.x branch, but I'm not sure how to resolve this in a way that suits the general user experience.

**Comment by smith4** [comment]
The root directory contains a sample-credentials.yml file. Rename it to credentials.yml and add your credentials to it. The deployment will use those values. This is the current solution for passing credentials.

**Comment by blint** [comment]
Well, the purpose is a bit different, according to what I've seen in the repo, it is passed _as is_ to Occopus. I could also use the Ansible questions mechanism, but I'm not sure if that prevents non-interactive deployment. I could also use templating to pass only the relevant parts of the credentials.yml to Occopus' auth_data.yml and pass the rest to the Zorp container. Or use a different config file for security altogether. Are there any other options that I have not thought of?

**Comment by blint** [comment]
Thanks, I temporarily added the security config parameters to the credentials.yml as well and map the resource subtree directly to the occopus config, which should be an equivalent transformation. With this conflicts are resolved and if you want, I modify the PR to point to a "security" branch, that can be merged to the current upstream at your convenience.

**Comment by blint** [comment]
I'm sending a new req based on the current development branch

**Pull request closed without merging**
